version: '3.0'
services:
   db:
      image: postgres
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGERS_DB: CompanyEmployee
      ports:
        - "5435:5432"
      restart: unless-stopped 
      container_name: postgres
   companyemployees:
     depends_on:
       - db
     image: ivan/companyemployees:runtime
     build:
       context: .
     container_name: companyemployees_api
     ports:
       - "5000:5000"
       - "5001:5001"
     environment:
       - ASPNETCORE_Kestrel__Certificates__Default__Password=awesomepass
       - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/companyemployees.pfx
     volumes: 
       - ${USERPROFILE}/.aspnet/https:/https/ 